apiVersion: v1
kind: PersistentVolume
metadata:
  name: surrealdb-devto-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-local-storage
  local:
    path: /opt/k8s-pers/vol1/surrealdb-devto
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - mgplcb05
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: surrealdb-devto-pvc
  namespace: devto-dedup
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-local-storage
  resources:
    requests:
      storage: 5Gi
